// Mocks generated by Mockito 5.4.6 from annotations
// in my_budget_client/test/unit/categories_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_budget_client/domain/entities/category.dart' as _i4;
import 'package:my_budget_client/domain/entities/transaction.dart' as _i6;
import 'package:my_budget_client/domain/repositories/category_repository.dart'
    as _i2;
import 'package:my_budget_client/domain/repositories/transaction_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i2.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Category>> watchCategories() =>
      (super.noSuchMethod(
            Invocation.method(#watchCategories, []),
            returnValue: _i3.Stream<List<_i4.Category>>.empty(),
          )
          as _i3.Stream<List<_i4.Category>>);

  @override
  _i3.Future<List<_i4.Category>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i3.Future<List<_i4.Category>>.value(<_i4.Category>[]),
          )
          as _i3.Future<List<_i4.Category>>);

  @override
  _i3.Future<_i4.Category?> getCategoryById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [id]),
            returnValue: _i3.Future<_i4.Category?>.value(),
          )
          as _i3.Future<_i4.Category?>);

  @override
  _i3.Future<void> addCategory(_i4.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#addCategory, [category]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCategory(_i4.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategory, [category]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCategory(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<Map<int, double>> watchCategoryTotals() =>
      (super.noSuchMethod(
            Invocation.method(#watchCategoryTotals, []),
            returnValue: _i3.Stream<Map<int, double>>.empty(),
          )
          as _i3.Stream<Map<int, double>>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i5.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i6.Transaction>> watchTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#watchTransactions, []),
            returnValue: _i3.Stream<List<_i6.Transaction>>.empty(),
          )
          as _i3.Stream<List<_i6.Transaction>>);

  @override
  _i3.Future<List<_i6.Transaction>> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: _i3.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i3.Future<List<_i6.Transaction>>);

  @override
  _i3.Future<List<_i6.Transaction>> getTransactionsByCategoryId(
    int? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByCategoryId, [categoryId]),
            returnValue: _i3.Future<List<_i6.Transaction>>.value(
              <_i6.Transaction>[],
            ),
          )
          as _i3.Future<List<_i6.Transaction>>);

  @override
  _i3.Future<_i6.Transaction?> getTransactionById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionById, [id]),
            returnValue: _i3.Future<_i6.Transaction?>.value(),
          )
          as _i3.Future<_i6.Transaction?>);

  @override
  _i3.Future<void> addTransaction(_i6.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#addTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTransaction(_i6.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
