// Mocks generated by Mockito 5.4.6 from annotations
// in my_budget_client/test/unit/currency_converter_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_budget_client/core/database/app_database.dart' as _i12;
import 'package:my_budget_client/domain/entities/account.dart' as _i8;
import 'package:my_budget_client/domain/entities/account_type.dart' as _i9;
import 'package:my_budget_client/domain/entities/currency.dart' as _i4;
import 'package:my_budget_client/domain/entities/currency_designation.dart'
    as _i5;
import 'package:my_budget_client/domain/entities/exchange_rate.dart' as _i6;
import 'package:my_budget_client/domain/repositories/account_repository.dart'
    as _i7;
import 'package:my_budget_client/domain/repositories/currency_repository.dart'
    as _i2;
import 'package:my_budget_client/domain/repositories/settings_repository.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CurrencyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyRepository extends _i1.Mock
    implements _i2.CurrencyRepository {
  MockCurrencyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Currency>> getCurrencies() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrencies, []),
            returnValue: _i3.Future<List<_i4.Currency>>.value(<_i4.Currency>[]),
          )
          as _i3.Future<List<_i4.Currency>>);

  @override
  _i3.Stream<List<_i4.Currency>> watchCurrencies() =>
      (super.noSuchMethod(
            Invocation.method(#watchCurrencies, []),
            returnValue: _i3.Stream<List<_i4.Currency>>.empty(),
          )
          as _i3.Stream<List<_i4.Currency>>);

  @override
  _i3.Future<_i4.Currency?> getCurrencyById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrencyById, [id]),
            returnValue: _i3.Future<_i4.Currency?>.value(),
          )
          as _i3.Future<_i4.Currency?>);

  @override
  _i3.Future<void> addCurrency(_i4.Currency? currency) =>
      (super.noSuchMethod(
            Invocation.method(#addCurrency, [currency]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCurrency(_i4.Currency? currency) =>
      (super.noSuchMethod(
            Invocation.method(#updateCurrency, [currency]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCurrency(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCurrency, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i5.CurrencyDesignation>>
  watchCurrencyDesignationsForCurrency(int? currencyId) =>
      (super.noSuchMethod(
            Invocation.method(#watchCurrencyDesignationsForCurrency, [
              currencyId,
            ]),
            returnValue: _i3.Stream<List<_i5.CurrencyDesignation>>.empty(),
          )
          as _i3.Stream<List<_i5.CurrencyDesignation>>);

  @override
  _i3.Future<List<_i5.CurrencyDesignation>> getCurrencyDesignationsForCurrency(
    int? currencyId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrencyDesignationsForCurrency, [
              currencyId,
            ]),
            returnValue: _i3.Future<List<_i5.CurrencyDesignation>>.value(
              <_i5.CurrencyDesignation>[],
            ),
          )
          as _i3.Future<List<_i5.CurrencyDesignation>>);

  @override
  _i3.Future<_i5.CurrencyDesignation?> getCurrencyDesignationById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrencyDesignationById, [id]),
            returnValue: _i3.Future<_i5.CurrencyDesignation?>.value(),
          )
          as _i3.Future<_i5.CurrencyDesignation?>);

  @override
  _i3.Stream<List<_i5.CurrencyDesignation>> watchAllCurrencyDesignations() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllCurrencyDesignations, []),
            returnValue: _i3.Stream<List<_i5.CurrencyDesignation>>.empty(),
          )
          as _i3.Stream<List<_i5.CurrencyDesignation>>);

  @override
  _i3.Future<List<_i5.CurrencyDesignation>> getAllCurrencyDesignations() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCurrencyDesignations, []),
            returnValue: _i3.Future<List<_i5.CurrencyDesignation>>.value(
              <_i5.CurrencyDesignation>[],
            ),
          )
          as _i3.Future<List<_i5.CurrencyDesignation>>);

  @override
  _i3.Stream<List<_i6.ExchangeRate>> watchAllExchangeRates() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllExchangeRates, []),
            returnValue: _i3.Stream<List<_i6.ExchangeRate>>.empty(),
          )
          as _i3.Stream<List<_i6.ExchangeRate>>);

  @override
  _i3.Future<void> addExchangeRate(_i6.ExchangeRate? exchangeRate) =>
      (super.noSuchMethod(
            Invocation.method(#addExchangeRate, [exchangeRate]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i7.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i8.Account>> getAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAccounts, []),
            returnValue: _i3.Future<List<_i8.Account>>.value(<_i8.Account>[]),
          )
          as _i3.Future<List<_i8.Account>>);

  @override
  _i3.Stream<List<_i8.Account>> watchAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#watchAccounts, []),
            returnValue: _i3.Stream<List<_i8.Account>>.empty(),
          )
          as _i3.Stream<List<_i8.Account>>);

  @override
  _i3.Future<_i8.Account?> getAccountById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountById, [id]),
            returnValue: _i3.Future<_i8.Account?>.value(),
          )
          as _i3.Future<_i8.Account?>);

  @override
  _i3.Future<void> addAccount(_i8.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [account]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateAccount(_i8.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccount, [account]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccount(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> restoreAccount(_i8.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#restoreAccount, [account]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i9.AccountType>> getAccountTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getAccountTypes, []),
            returnValue: _i3.Future<List<_i9.AccountType>>.value(
              <_i9.AccountType>[],
            ),
          )
          as _i3.Future<List<_i9.AccountType>>);

  @override
  _i3.Stream<List<_i9.AccountType>> watchAccountTypes() =>
      (super.noSuchMethod(
            Invocation.method(#watchAccountTypes, []),
            returnValue: _i3.Stream<List<_i9.AccountType>>.empty(),
          )
          as _i3.Stream<List<_i9.AccountType>>);

  @override
  _i3.Future<_i9.AccountType?> getAccountTypeById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountTypeById, [id]),
            returnValue: _i3.Future<_i9.AccountType?>.value(),
          )
          as _i3.Future<_i9.AccountType?>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i10.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i11.ThemeMode> get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i3.Stream<_i11.ThemeMode>.empty(),
          )
          as _i3.Stream<_i11.ThemeMode>);

  @override
  _i3.Future<void> setThemeMode(_i11.ThemeMode? themeMode) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [themeMode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i12.Setting?> watchSetting(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#watchSetting, [key]),
            returnValue: _i3.Stream<_i12.Setting?>.empty(),
          )
          as _i3.Stream<_i12.Setting?>);

  @override
  _i3.Future<void> setSetting(_i12.Setting? setting) =>
      (super.noSuchMethod(
            Invocation.method(#setSetting, [setting]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
