// Mocks generated by Mockito 5.4.6 from annotations
// in my_budget_client/test/unit/currency_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_budget_client/domain/entities/currency.dart' as _i4;
import 'package:my_budget_client/domain/repositories/currency_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CurrencyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyRepository extends _i1.Mock
    implements _i2.CurrencyRepository {
  MockCurrencyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Currency>> getCurrencies() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrencies, []),
            returnValue: _i3.Future<List<_i4.Currency>>.value(<_i4.Currency>[]),
          )
          as _i3.Future<List<_i4.Currency>>);

  @override
  _i3.Stream<List<_i4.Currency>> watchCurrencies() =>
      (super.noSuchMethod(
            Invocation.method(#watchCurrencies, []),
            returnValue: _i3.Stream<List<_i4.Currency>>.empty(),
          )
          as _i3.Stream<List<_i4.Currency>>);

  @override
  _i3.Future<_i4.Currency?> getCurrencyById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrencyById, [id]),
            returnValue: _i3.Future<_i4.Currency?>.value(),
          )
          as _i3.Future<_i4.Currency?>);

  @override
  _i3.Future<void> addCurrency(_i4.Currency? currency) =>
      (super.noSuchMethod(
            Invocation.method(#addCurrency, [currency]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCurrency(_i4.Currency? currency) =>
      (super.noSuchMethod(
            Invocation.method(#updateCurrency, [currency]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCurrency(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCurrency, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
