import 'package:flutter/material.dart';
import 'package:my_budget_client/core/theme/app_theme.dart';
import 'package:my_budget_client/domain/entities/custom_theme.dart';

final List<CustomTheme> defaultThemePresets = [
  const CustomTheme(
    id: 'classic-blue',
    name: 'Classic Blue',
    primaryColor: Color(0xFF2196F3),
    secondaryColor: Color(0xFF9C27B0),
    surfaceColor: Color(0xFF1E1E1E),
    backgroundColor: Color(0xFF121212),
    windowEffectType: WindowEffectType.none,
    themeMode: ThemeMode.dark,
    isPreset: true,
  ),
  const CustomTheme(
    id: 'midnight',
    name: 'Midnight',
    primaryColor: Color(0xFF3F51B5),
    secondaryColor: Color(0xFFFF4081),
    surfaceColor: Color(0xFF121212),
    backgroundColor: Color(0xFF000000),
    windowEffectType: WindowEffectType.acrylic,
    effectOpacity: 0.6,
    themeMode: ThemeMode.dark,
    isPreset: true,
  ),
  const CustomTheme(
    id: 'emerald',
    name: 'Emerald Coast',
    primaryColor: Color(0xFF009688),
    secondaryColor: Color(0xFFCDDC39),
    surfaceColor: Color(0xFF1B262C),
    backgroundColor: Color(0xFF0F4C75),
    windowEffectType: WindowEffectType.mica,
    themeMode: ThemeMode.dark,
    isPreset: true,
  ),
  const CustomTheme(
    id: 'aero-glass',
    name: 'Aero Glass',
    primaryColor: Color(0xFF607D8B),
    secondaryColor: Color(0xFF03A9F4),
    surfaceColor: Color(0x33FFFFFF),
    backgroundColor: Color(0x11000000),
    windowEffectType: WindowEffectType.aero,
    effectOpacity: 0.1,
    surfaceOpacity: 0.2,
    themeMode: ThemeMode.system,
    isPreset: true,
  ),
  const CustomTheme(
    id: 'doodle-dark',
    name: 'Doodles',
    primaryColor: Color(0xFF5C6BC0),
    secondaryColor: Color(0xFFFFCA28),
    surfaceColor: Color(0xFF1A1A2E),
    backgroundColor: Color(0xFF0F0F1E),
    backgroundImagePath: 'assets/backgrounds/pattern_doodles_dark.png',
    backgroundImageOpacity: 0.15,
    windowEffectType: WindowEffectType.mica,
    themeMode: ThemeMode.dark,
    isPreset: true,
  ),
  const CustomTheme(
    id: 'pastel-vibes',
    name: 'Pastel Vibes',
    primaryColor: Color(0xFFF48FB1),
    secondaryColor: Color(0xFF80DEEA),
    surfaceColor: Color(0xFFFFF0F5),
    backgroundColor: Color(0xFFFAFAFA),
    backgroundImagePath: 'assets/backgrounds/pattern_geometric_pastel.png',
    backgroundImageOpacity: 0.5,
    windowEffectType: WindowEffectType.mica,
    themeMode: ThemeMode.light,
    isPreset: true,
  ),
  const CustomTheme(
    id: 'nebula-dreams',
    name: 'Nebula',
    primaryColor: Color(0xFF7E57C2),
    secondaryColor: Color(0xFF26A69A),
    surfaceColor: Color(0xFF120024),
    backgroundColor: Color(0xFF0A0014),
    backgroundImagePath: 'assets/backgrounds/pattern_nebula.png',
    backgroundImageOpacity: 0.4,
    windowEffectType: WindowEffectType.acrylic,
    effectOpacity: 0.7,
    themeMode: ThemeMode.dark,
    isPreset: true,
  ),
];
