import 'package:flutter_test/flutter_test.dart';
import 'package:drift/native.dart';
import 'package:my_budget_client/core/database/app_database.dart' hide Category;
import 'package:my_budget_client/data/repositories/local_db/local_category_repository.dart';
import 'package:my_budget_client/domain/entities/category.dart';
import 'package:my_budget_client/domain/repositories/category_repository.dart';

void main() {
  late AppDatabase database;
  late CategoryRepository categoryRepository;

  setUp(() {
    database = AppDatabase.forTesting(NativeDatabase.memory());
    categoryRepository = LocalCategoryRepository(database);
  });

  tearDown(() async {
    await database.close();
  });

  test('Repository should add a category and then read it', () async {
    // Arrange
    final newCategory = Category(name: 'Groceries', parentId: null);

    // Act
    await categoryRepository.addCategory(newCategory);

    // Since we don't know the assigned ID, we fetch all categories to find the one we added.
    final allCategories = await categoryRepository.getCategories();
    final foundCategory = allCategories.firstWhere((c) => c.name == 'Groceries');

    // Assert
    expect(allCategories, isNotEmpty);
    expect(foundCategory, isNotNull);
    expect(foundCategory.name, 'Groceries');
    // The ID should be generated by the database, so it should be a non-null integer.
    expect(foundCategory.id, isNotNull);
    expect(foundCategory.id, isA<int>());
  });

  test('Repository should update a category', () async {
    // Arrange
    final initialCategory = Category(name: 'Shopping', parentId: null);
    await categoryRepository.addCategory(initialCategory);
    final savedCategory = (await categoryRepository.getCategories()).first;

    final updatedCategory = savedCategory.copyWith(name: 'General Shopping');

    // Act
    await categoryRepository.updateCategory(updatedCategory);
    final foundCategory = await categoryRepository.getCategoryById(savedCategory.id!);

    // Assert
    expect(foundCategory, isNotNull);
    expect(foundCategory!.name, 'General Shopping');
  });

  test('Repository should delete a category', () async {
    // Arrange
    final categoryToDelete = Category(name: 'To be deleted', parentId: null);
    await categoryRepository.addCategory(categoryToDelete);
    final savedCategory = (await categoryRepository.getCategories()).first;

    // Act
    await categoryRepository.deleteCategory(savedCategory.id!);
    final foundCategory = await categoryRepository.getCategoryById(savedCategory.id!);

    // Assert
    expect(foundCategory, isNull);
  });

  test('Repository should get all categories', () async {
    // Arrange
    await categoryRepository.addCategory(Category(name: 'Food', parentId: null));
    await categoryRepository.addCategory(Category(name: 'Transport', parentId: null));

    // Act
    final allCategories = await categoryRepository.getCategories();

    // Assert
    expect(allCategories.length, 2);
    expect(allCategories.any((c) => c.name == 'Food'), isTrue);
    expect(allCategories.any((c) => c.name == 'Transport'), isTrue);
  });
}
