version: '3.8'

services:
  server:
    build: .
    restart: always
    ports:
      - '58080:8080'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/my_budget
      - DART_FROG_ENV=production
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_budget
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my_budget"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
