// Mocks generated by Mockito 5.4.6 from annotations
// in my_budget_client/test/presentation/blocs/add_edit_transaction_subscriptions_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_budget_client/core/enums/filter_enums.dart' as _i11;
import 'package:my_budget_client/domain/entities/account.dart' as _i4;
import 'package:my_budget_client/domain/entities/account_type.dart' as _i5;
import 'package:my_budget_client/domain/entities/asset_data.dart' as _i20;
import 'package:my_budget_client/domain/entities/category.dart' as _i7;
import 'package:my_budget_client/domain/entities/category_with_total.dart'
    as _i8;
import 'package:my_budget_client/domain/entities/currency.dart' as _i13;
import 'package:my_budget_client/domain/entities/currency_designation.dart'
    as _i14;
import 'package:my_budget_client/domain/entities/exchange_rate.dart' as _i15;
import 'package:my_budget_client/domain/entities/settings.dart' as _i18;
import 'package:my_budget_client/domain/entities/transaction.dart' as _i10;
import 'package:my_budget_client/domain/repositories/account_repository.dart'
    as _i2;
import 'package:my_budget_client/domain/repositories/asset_repository.dart'
    as _i19;
import 'package:my_budget_client/domain/repositories/category_repository.dart'
    as _i6;
import 'package:my_budget_client/domain/repositories/currency_repository.dart'
    as _i12;
import 'package:my_budget_client/domain/repositories/settings_repository.dart'
    as _i16;
import 'package:my_budget_client/domain/repositories/transaction_repository.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i2.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Account>> getAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAccounts, []),
            returnValue: _i3.Future<List<_i4.Account>>.value(<_i4.Account>[]),
          )
          as _i3.Future<List<_i4.Account>>);

  @override
  _i3.Future<List<_i4.Account>> getAccountsPaginated({
    int? limit = 10,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountsPaginated, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i3.Future<List<_i4.Account>>.value(<_i4.Account>[]),
          )
          as _i3.Future<List<_i4.Account>>);

  @override
  _i3.Future<List<_i4.Account>> getAccountsPaginatedFiltered({
    int? limit = 10,
    int? offset = 0,
    _i2.AccountFilters? accountFilters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountsPaginatedFiltered, [], {
              #limit: limit,
              #offset: offset,
              #accountFilters: accountFilters,
            }),
            returnValue: _i3.Future<List<_i4.Account>>.value(<_i4.Account>[]),
          )
          as _i3.Future<List<_i4.Account>>);

  @override
  _i3.Stream<List<_i4.Account>> watchAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#watchAccounts, []),
            returnValue: _i3.Stream<List<_i4.Account>>.empty(),
          )
          as _i3.Stream<List<_i4.Account>>);

  @override
  _i3.Future<_i4.Account?> getAccountById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountById, [id]),
            returnValue: _i3.Future<_i4.Account?>.value(),
          )
          as _i3.Future<_i4.Account?>);

  @override
  _i3.Future<List<_i4.Account>> getAccountsByIds(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountsByIds, [ids]),
            returnValue: _i3.Future<List<_i4.Account>>.value(<_i4.Account>[]),
          )
          as _i3.Future<List<_i4.Account>>);

  @override
  _i3.Future<void> addAccount(_i4.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [account]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addAccounts(List<_i4.Account>? accounts) =>
      (super.noSuchMethod(
            Invocation.method(#addAccounts, [accounts]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateAccount(_i4.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccount, [account]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccount(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMultipleAccounts(List<String>? accountIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMultipleAccounts, [accountIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccountWithTransactions(String? accountId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccountWithTransactions, [accountId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccountAndReassignTransactions(
    String? accountId,
    String? newAccountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccountAndReassignTransactions, [
              accountId,
              newAccountId,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> restoreAccount(_i4.Account? account) =>
      (super.noSuchMethod(
            Invocation.method(#restoreAccount, [account]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, double>> getBalancesAtDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getBalancesAtDate, [date]),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);

  @override
  _i3.Future<int> getCountWithFilters({List<String>? accountTypeIds}) =>
      (super.noSuchMethod(
            Invocation.method(#getCountWithFilters, [], {
              #accountTypeIds: accountTypeIds,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i5.AccountType>> getAccountTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getAccountTypes, []),
            returnValue: _i3.Future<List<_i5.AccountType>>.value(
              <_i5.AccountType>[],
            ),
          )
          as _i3.Future<List<_i5.AccountType>>);

  @override
  _i3.Stream<List<_i5.AccountType>> watchAccountTypes() =>
      (super.noSuchMethod(
            Invocation.method(#watchAccountTypes, []),
            returnValue: _i3.Stream<List<_i5.AccountType>>.empty(),
          )
          as _i3.Stream<List<_i5.AccountType>>);

  @override
  _i3.Future<_i5.AccountType?> getAccountTypeById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountTypeById, [id]),
            returnValue: _i3.Future<_i5.AccountType?>.value(),
          )
          as _i3.Future<_i5.AccountType?>);

  @override
  _i3.Future<void> addAccountTypes(List<_i5.AccountType>? accountTypes) =>
      (super.noSuchMethod(
            Invocation.method(#addAccountTypes, [accountTypes]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateAccountTypeForMultipleAccounts(
    List<String>? accountIds,
    String? accountTypeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccountTypeForMultipleAccounts, [
              accountIds,
              accountTypeId,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i6.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i7.Category>> watchCategories({
    bool? includeSystem = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchCategories, [], {
              #includeSystem: includeSystem,
            }),
            returnValue: _i3.Stream<List<_i7.Category>>.empty(),
          )
          as _i3.Stream<List<_i7.Category>>);

  @override
  _i3.Future<List<_i7.Category>> getCategories({bool? includeSystem = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, [], {
              #includeSystem: includeSystem,
            }),
            returnValue: _i3.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i3.Future<List<_i7.Category>>);

  @override
  _i3.Future<List<_i7.Category>> getCategoriesPaginated({
    int? limit = 10,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoriesPaginated, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i3.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i3.Future<List<_i7.Category>>);

  @override
  _i3.Future<List<_i8.CategoryWithTotal>> getCategoriesWithTotalsPaginated({
    int? limit = 50,
    int? offset = 0,
    _i6.CategoryFilters? filters = const _i6.CategoryFilters(),
    DateTime? dateFrom,
    DateTime? dateTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoriesWithTotalsPaginated, [], {
              #limit: limit,
              #offset: offset,
              #filters: filters,
              #dateFrom: dateFrom,
              #dateTo: dateTo,
            }),
            returnValue: _i3.Future<List<_i8.CategoryWithTotal>>.value(
              <_i8.CategoryWithTotal>[],
            ),
          )
          as _i3.Future<List<_i8.CategoryWithTotal>>);

  @override
  _i3.Future<_i7.Category?> getCategoryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [id]),
            returnValue: _i3.Future<_i7.Category?>.value(),
          )
          as _i3.Future<_i7.Category?>);

  @override
  _i3.Future<List<_i7.Category>> getCategoriesByIds(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoriesByIds, [ids]),
            returnValue: _i3.Future<List<_i7.Category>>.value(<_i7.Category>[]),
          )
          as _i3.Future<List<_i7.Category>>);

  @override
  _i3.Future<void> addCategory(_i7.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#addCategory, [category]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addCategories(List<_i7.Category>? categories) =>
      (super.noSuchMethod(
            Invocation.method(#addCategories, [categories]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCategory(_i7.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategory, [category]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCategoryWithTransactions(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategoryWithTransactions, [categoryId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCategoryAndReassignTransactions(
    String? categoryId,
    String? newCategoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategoryAndReassignTransactions, [
              categoryId,
              newCategoryId,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i9.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i10.Transaction>> watchTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#watchTransactions, []),
            returnValue: _i3.Stream<List<_i10.Transaction>>.empty(),
          )
          as _i3.Stream<List<_i10.Transaction>>);

  @override
  _i3.Future<List<_i10.Transaction>> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: _i3.Future<List<_i10.Transaction>>.value(
              <_i10.Transaction>[],
            ),
          )
          as _i3.Future<List<_i10.Transaction>>);

  @override
  _i3.Future<List<_i10.Transaction>> getTransactionsPaginated({
    int? limit = 10,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsPaginated, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i3.Future<List<_i10.Transaction>>.value(
              <_i10.Transaction>[],
            ),
          )
          as _i3.Future<List<_i10.Transaction>>);

  @override
  _i3.Future<List<_i10.Transaction>> getTransactionsWithFilters({
    int? limit = 10,
    int? offset = 0,
    _i11.Sort? sort = _i11.Sort.descending,
    _i9.TransactionFilters? filters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsWithFilters, [], {
              #limit: limit,
              #offset: offset,
              #sort: sort,
              #filters: filters,
            }),
            returnValue: _i3.Future<List<_i10.Transaction>>.value(
              <_i10.Transaction>[],
            ),
          )
          as _i3.Future<List<_i10.Transaction>>);

  @override
  _i3.Future<List<_i10.Transaction>> getTransactionsByCategoryId(
    String? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByCategoryId, [categoryId]),
            returnValue: _i3.Future<List<_i10.Transaction>>.value(
              <_i10.Transaction>[],
            ),
          )
          as _i3.Future<List<_i10.Transaction>>);

  @override
  _i3.Future<_i10.Transaction?> getTransactionById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionById, [id]),
            returnValue: _i3.Future<_i10.Transaction?>.value(),
          )
          as _i3.Future<_i10.Transaction?>);

  @override
  _i3.Future<void> addTransaction(_i10.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#addTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addTransactions(List<_i10.Transaction>? transactions) =>
      (super.noSuchMethod(
            Invocation.method(#addTransactions, [transactions]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTransaction(_i10.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTransaction(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMultipleTransactions(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMultipleTransactions, [ids]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateDateForMultipleTransactions(
    List<String>? ids,
    DateTime? newDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDateForMultipleTransactions, [
              ids,
              newDate,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCategoryForMultipleTransactions(
    List<String>? ids,
    String? newCategoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategoryForMultipleTransactions, [
              ids,
              newCategoryId,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getCountWithFilters({_i9.TransactionFilters? filters}) =>
      (super.noSuchMethod(
            Invocation.method(#getCountWithFilters, [], {#filters: filters}),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> getAllCount() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i9.GroupedTransactionTotal>> getTransactionTotalsGrouped({
    DateTime? dateFrom,
    DateTime? dateTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionTotalsGrouped, [], {
              #dateFrom: dateFrom,
              #dateTo: dateTo,
            }),
            returnValue: _i3.Future<List<_i9.GroupedTransactionTotal>>.value(
              <_i9.GroupedTransactionTotal>[],
            ),
          )
          as _i3.Future<List<_i9.GroupedTransactionTotal>>);

  @override
  _i3.Future<Map<String, double>> getCategoryTotalsInMainCurrency({
    DateTime? dateFrom,
    DateTime? dateTo,
    required String? mainCurrencyCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryTotalsInMainCurrency, [], {
              #dateFrom: dateFrom,
              #dateTo: dateTo,
              #mainCurrencyCode: mainCurrencyCode,
            }),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);

  @override
  _i3.Future<void> restoreTransactions(List<_i10.Transaction>? transactions) =>
      (super.noSuchMethod(
            Invocation.method(#restoreTransactions, [transactions]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [CurrencyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyRepository extends _i1.Mock
    implements _i12.CurrencyRepository {
  MockCurrencyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i13.Currency>> getCurrencies() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrencies, []),
            returnValue: _i3.Future<List<_i13.Currency>>.value(
              <_i13.Currency>[],
            ),
          )
          as _i3.Future<List<_i13.Currency>>);

  @override
  _i3.Stream<List<_i13.Currency>> watchCurrencies() =>
      (super.noSuchMethod(
            Invocation.method(#watchCurrencies, []),
            returnValue: _i3.Stream<List<_i13.Currency>>.empty(),
          )
          as _i3.Stream<List<_i13.Currency>>);

  @override
  _i3.Future<_i13.Currency?> getCurrencyByCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrencyByCode, [code]),
            returnValue: _i3.Future<_i13.Currency?>.value(),
          )
          as _i3.Future<_i13.Currency?>);

  @override
  _i3.Future<void> addCurrency(_i13.Currency? currency) =>
      (super.noSuchMethod(
            Invocation.method(#addCurrency, [currency]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addCurrencies(List<_i13.Currency>? currencies) =>
      (super.noSuchMethod(
            Invocation.method(#addCurrencies, [currencies]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCurrency(_i13.Currency? currency) =>
      (super.noSuchMethod(
            Invocation.method(#updateCurrency, [currency]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCurrency(_i13.Currency? currency) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCurrency, [currency]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i14.CurrencyDesignation>>
  watchCurrencyDesignationsForCurrency(String? currencyCode) =>
      (super.noSuchMethod(
            Invocation.method(#watchCurrencyDesignationsForCurrency, [
              currencyCode,
            ]),
            returnValue: _i3.Stream<List<_i14.CurrencyDesignation>>.empty(),
          )
          as _i3.Stream<List<_i14.CurrencyDesignation>>);

  @override
  _i3.Future<List<_i14.CurrencyDesignation>> getCurrencyDesignationsForCurrency(
    String? currencyCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrencyDesignationsForCurrency, [
              currencyCode,
            ]),
            returnValue: _i3.Future<List<_i14.CurrencyDesignation>>.value(
              <_i14.CurrencyDesignation>[],
            ),
          )
          as _i3.Future<List<_i14.CurrencyDesignation>>);

  @override
  _i3.Future<_i14.CurrencyDesignation?> getCurrencyDesignationById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrencyDesignationById, [id]),
            returnValue: _i3.Future<_i14.CurrencyDesignation?>.value(),
          )
          as _i3.Future<_i14.CurrencyDesignation?>);

  @override
  _i3.Future<void> addCurrencyDesignation(
    _i14.CurrencyDesignation? designation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addCurrencyDesignation, [designation]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i14.CurrencyDesignation>> watchAllCurrencyDesignations() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllCurrencyDesignations, []),
            returnValue: _i3.Stream<List<_i14.CurrencyDesignation>>.empty(),
          )
          as _i3.Stream<List<_i14.CurrencyDesignation>>);

  @override
  _i3.Future<List<_i14.CurrencyDesignation>> getAllCurrencyDesignations() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCurrencyDesignations, []),
            returnValue: _i3.Future<List<_i14.CurrencyDesignation>>.value(
              <_i14.CurrencyDesignation>[],
            ),
          )
          as _i3.Future<List<_i14.CurrencyDesignation>>);

  @override
  _i3.Future<List<_i15.ExchangeRateDomain>> getLatestExchangeRates(
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestExchangeRates, [date]),
            returnValue: _i3.Future<List<_i15.ExchangeRateDomain>>.value(
              <_i15.ExchangeRateDomain>[],
            ),
          )
          as _i3.Future<List<_i15.ExchangeRateDomain>>);

  @override
  _i3.Future<List<_i15.ExchangeRateDomain>> getLatestExchangeRatesAll() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestExchangeRatesAll, []),
            returnValue: _i3.Future<List<_i15.ExchangeRateDomain>>.value(
              <_i15.ExchangeRateDomain>[],
            ),
          )
          as _i3.Future<List<_i15.ExchangeRateDomain>>);

  @override
  _i3.Future<List<_i15.ExchangeRateDomain>> getLatestExchangeRatesByList(
    List<DateTime>? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestExchangeRatesByList, [date]),
            returnValue: _i3.Future<List<_i15.ExchangeRateDomain>>.value(
              <_i15.ExchangeRateDomain>[],
            ),
          )
          as _i3.Future<List<_i15.ExchangeRateDomain>>);

  @override
  _i3.Future<List<_i15.ExchangeRateDomain>> getExchangeRatesFiltered({
    int? limit = 100,
    int? offset = 0,
    DateTime? startDate,
    DateTime? endDate,
    String? fromCurrency,
    String? toCurrency,
    List<int>? presets,
    bool? sortAscending = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExchangeRatesFiltered, [], {
              #limit: limit,
              #offset: offset,
              #startDate: startDate,
              #endDate: endDate,
              #fromCurrency: fromCurrency,
              #toCurrency: toCurrency,
              #presets: presets,
              #sortAscending: sortAscending,
            }),
            returnValue: _i3.Future<List<_i15.ExchangeRateDomain>>.value(
              <_i15.ExchangeRateDomain>[],
            ),
          )
          as _i3.Future<List<_i15.ExchangeRateDomain>>);

  @override
  _i3.Future<int> getExchangeRatesCount({
    DateTime? startDate,
    DateTime? endDate,
    String? fromCurrency,
    String? toCurrency,
    List<int>? presets,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExchangeRatesCount, [], {
              #startDate: startDate,
              #endDate: endDate,
              #fromCurrency: fromCurrency,
              #toCurrency: toCurrency,
              #presets: presets,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> deleteExchangeRates(List<_i15.ExchangeRateDomain>? rates) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExchangeRates, [rates]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateExchangeRatePresets(
    List<_i15.ExchangeRateDomain>? rates,
    int? newPreset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateExchangeRatePresets, [rates, newPreset]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<int>> getAvailablePresets() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailablePresets, []),
            returnValue: _i3.Future<List<int>>.value(<int>[]),
          )
          as _i3.Future<List<int>>);

  @override
  _i3.Future<void> addExchangeRate(_i15.ExchangeRateDomain? exchangeRate) =>
      (super.noSuchMethod(
            Invocation.method(#addExchangeRate, [exchangeRate]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addExchangeRates(
    List<_i15.ExchangeRateDomain>? exchangeRates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addExchangeRates, [exchangeRates]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateExchangeRate(_i15.ExchangeRateDomain? exchangeRate) =>
      (super.noSuchMethod(
            Invocation.method(#updateExchangeRate, [exchangeRate]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i16.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i17.ThemeMode> get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i3.Stream<_i17.ThemeMode>.empty(),
          )
          as _i3.Stream<_i17.ThemeMode>);

  @override
  _i3.Future<void> setThemeMode(_i17.ThemeMode? themeMode, String? device) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [themeMode, device]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveThemeMode(_i17.ThemeMode? themeMode) =>
      (super.noSuchMethod(
            Invocation.method(#saveThemeMode, [themeMode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i18.Settings>> watchAllSettings() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllSettings, []),
            returnValue: _i3.Stream<List<_i18.Settings>>.empty(),
          )
          as _i3.Stream<List<_i18.Settings>>);

  @override
  _i3.Stream<_i18.Settings?> watchSetting(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#watchSetting, [key]),
            returnValue: _i3.Stream<_i18.Settings?>.empty(),
          )
          as _i3.Stream<_i18.Settings?>);

  @override
  _i3.Future<_i18.Settings?> getSetting(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getSetting, [key]),
            returnValue: _i3.Future<_i18.Settings?>.value(),
          )
          as _i3.Future<_i18.Settings?>);

  @override
  _i3.Future<void> setSetting(_i18.Settings? setting) =>
      (super.noSuchMethod(
            Invocation.method(#setSetting, [setting]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String>> getAllSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSettings, []),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<void> saveSetting(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveSetting, [key, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> initializeDefaults() =>
      (super.noSuchMethod(
            Invocation.method(#initializeDefaults, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AssetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssetRepository extends _i1.Mock implements _i19.AssetRepository {
  MockAssetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i20.AssetDataDomain>> getAssetData({
    int? limit = 50,
    int? offset = 0,
    String? assetId,
    String? accountId,
    DateTime? startDate,
    DateTime? endDate,
    String? name,
    List<String>? assetTypes,
    String? description,
    List<String>? currencyCodes,
    List<String>? sources,
    List<int>? presets,
    double? minValue,
    double? maxValue,
    bool? sortAscending = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAssetData, [], {
              #limit: limit,
              #offset: offset,
              #assetId: assetId,
              #accountId: accountId,
              #startDate: startDate,
              #endDate: endDate,
              #name: name,
              #assetTypes: assetTypes,
              #description: description,
              #currencyCodes: currencyCodes,
              #sources: sources,
              #presets: presets,
              #minValue: minValue,
              #maxValue: maxValue,
              #sortAscending: sortAscending,
            }),
            returnValue: _i3.Future<List<_i20.AssetDataDomain>>.value(
              <_i20.AssetDataDomain>[],
            ),
          )
          as _i3.Future<List<_i20.AssetDataDomain>>);

  @override
  _i3.Stream<List<_i20.AssetDataDomain>> watchAssetData({
    int? limit = 50,
    int? offset = 0,
    String? assetId,
    String? accountId,
    DateTime? startDate,
    DateTime? endDate,
    String? name,
    List<String>? assetTypes,
    String? description,
    List<String>? currencyCodes,
    List<String>? sources,
    List<int>? presets,
    double? minValue,
    double? maxValue,
    bool? sortAscending = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchAssetData, [], {
              #limit: limit,
              #offset: offset,
              #assetId: assetId,
              #accountId: accountId,
              #startDate: startDate,
              #endDate: endDate,
              #name: name,
              #assetTypes: assetTypes,
              #description: description,
              #currencyCodes: currencyCodes,
              #sources: sources,
              #presets: presets,
              #minValue: minValue,
              #maxValue: maxValue,
              #sortAscending: sortAscending,
            }),
            returnValue: _i3.Stream<List<_i20.AssetDataDomain>>.empty(),
          )
          as _i3.Stream<List<_i20.AssetDataDomain>>);

  @override
  _i3.Future<void> addAssetData(_i20.AssetDataDomain? data) =>
      (super.noSuchMethod(
            Invocation.method(#addAssetData, [data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateAssetData(_i20.AssetDataDomain? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateAssetData, [data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAssetData(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAssetData, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAssets(List<String>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAssets, [ids]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getAvailableAssetIds() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableAssetIds, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> getAvailableAssetTypes() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableAssetTypes, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> getAvailableSources() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableSources, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<int>> getAvailablePresets() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailablePresets, []),
            returnValue: _i3.Future<List<int>>.value(<int>[]),
          )
          as _i3.Future<List<int>>);

  @override
  _i3.Future<int> getAssetDataCount({
    String? assetId,
    String? accountId,
    DateTime? startDate,
    DateTime? endDate,
    String? name,
    List<String>? assetTypes,
    String? description,
    List<String>? currencyCodes,
    List<String>? sources,
    List<int>? presets,
    double? minValue,
    double? maxValue,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAssetDataCount, [], {
              #assetId: assetId,
              #accountId: accountId,
              #startDate: startDate,
              #endDate: endDate,
              #name: name,
              #assetTypes: assetTypes,
              #description: description,
              #currencyCodes: currencyCodes,
              #sources: sources,
              #presets: presets,
              #minValue: minValue,
              #maxValue: maxValue,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
