import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:my_budget_client/domain/entities/transaction.dart';
import 'package:my_budget_client/presentation/blocs/transactions/transactions_bloc.dart';
import 'package:my_budget_client/presentation/blocs/accounts/accounts_bloc.dart';
import 'package:my_budget_client/presentation/blocs/categories/categories_bloc.dart';

class TransactionsScreen extends StatelessWidget {
  const TransactionsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Transactions'),
      ),
      body: BlocBuilder<TransactionsBloc, TransactionsState>(
        builder: (context, state) {
          if (state is TransactionsLoadInProgress) {
            return const Center(child: CircularProgressIndicator());
          }
          if (state is TransactionsLoadSuccess) {
            if (state.transactions.isEmpty) {
              return const Center(child: Text('No transactions yet.'));
            }
            return ListView.builder(
              itemCount: state.transactions.length,
              itemBuilder: (context, index) {
                final transaction = state.transactions[index];
                return ListTile(
                  title: Text(transaction.description),
                  subtitle: Text(
                      '${transaction.amount} on ${transaction.date.toLocal()}'),
                  onTap: () {
                    _showAddEditTransactionDialog(context,
                        transaction: transaction);
                  },
                  trailing: IconButton(
                    icon: const Icon(Icons.delete, color: Colors.redAccent),
                    onPressed: () {
                      context
                          .read<TransactionsBloc>()
                          .add(DeleteTransaction(transaction.id));
                    },
                  ),
                );
              },
            );
          }
          return const Center(child: Text('Failed to load transactions.'));
        },
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          _showAddEditTransactionDialog(context);
        },
        child: const Icon(Icons.add),
      ),
    );
  }

  void _showAddEditTransactionDialog(BuildContext context,
      {Transaction? transaction}) {
    showDialog(
      context: context,
      builder: (dialogContext) {
        return MultiBlocProvider(
          providers: [
            BlocProvider.value(
              value: BlocProvider.of<TransactionsBloc>(context),
            ),
            BlocProvider.value(
              value: BlocProvider.of<AccountsBloc>(context),
            ),
            BlocProvider.value(
              value: BlocProvider.of<CategoriesBloc>(context),
            ),
          ],
          child: AddEditTransactionDialog(transaction: transaction),
        );
      },
    );
  }
}

class AddEditTransactionDialog extends StatefulWidget {
  final Transaction? transaction;

  const AddEditTransactionDialog({super.key, this.transaction});

  @override
  State<AddEditTransactionDialog> createState() =>
      _AddEditTransactionDialogState();
}

class _AddEditTransactionDialogState extends State<AddEditTransactionDialog> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _descriptionController;
  late TextEditingController _amountController;
  int? _selectedAccountId;
  int? _selectedCategoryId;
  DateTime _selectedDate = DateTime.now();

  @override
  void initState() {
    super.initState();
    _descriptionController =
        TextEditingController(text: widget.transaction?.description);
    _amountController =
        TextEditingController(text: widget.transaction?.amount.toString());
    _selectedAccountId = widget.transaction?.accountId;
    _selectedCategoryId = widget.transaction?.categoryId;
    _selectedDate = widget.transaction?.date ?? DateTime.now();
  }

  @override
  void dispose() {
    _descriptionController.dispose();
    _amountController.dispose();
    super.dispose();
  }

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime(2000),
      lastDate: DateTime(2101),
    );
    if (picked != null && picked != _selectedDate) {
      setState(() {
        _selectedDate = picked;
      });
    }
  }

  void _onSave() {
    if (_formKey.currentState!.validate()) {
      final description = _descriptionController.text;
      final amount = double.parse(_amountController.text);

      if (widget.transaction == null) {
        // This is not quite right, because the transaction ID should be generated by the database
        // and the currency ID should be taken from the account.
        // For now, we will just create a new transaction with a dummy ID and currency ID.
        final newTransaction = Transaction(
          id: DateTime.now().millisecondsSinceEpoch,
          description: description,
          amount: amount,
          date: _selectedDate,
          accountId: _selectedAccountId!,
          categoryId: _selectedCategoryId!,
          currencyId: 1, // Dummy currency ID
        );
        context.read<TransactionsBloc>().add(AddTransaction(newTransaction));
      } else {
        final updatedTransaction = widget.transaction!.copyWith(
          description: description,
          amount: amount,
          date: _selectedDate,
          accountId: _selectedAccountId,
          categoryId: _selectedCategoryId,
        );
        context
            .read<TransactionsBloc>()
            .add(UpdateTransaction(updatedTransaction));
      }
      Navigator.of(context).pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text(
          widget.transaction == null ? 'Add Transaction' : 'Edit Transaction'),
      content: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TextFormField(
                controller: _descriptionController,
                decoration: const InputDecoration(labelText: 'Description'),
                validator: (value) => (value == null || value.isEmpty)
                    ? 'Please enter a description'
                    : null,
              ),
              TextFormField(
                controller: _amountController,
                decoration: const InputDecoration(labelText: 'Amount'),
                keyboardType: TextInputType.number,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter an amount';
                  }
                  if (double.tryParse(value) == null) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
              ),
              BlocBuilder<AccountsBloc, AccountsState>(
                builder: (context, state) {
                  if (state is AccountsLoadSuccess) {
                    return DropdownButtonFormField<int>(
                      initialValue: _selectedAccountId,
                      decoration: const InputDecoration(labelText: 'Account'),
                      items: state.accounts
                          .map((acc) => DropdownMenuItem<int>(
                                value: acc.id,
                                child: Text(acc.name),
                              ))
                          .toList(),
                      onChanged: (v) => setState(() => _selectedAccountId = v),
                      validator: (v) =>
                          v == null ? 'Please select an account' : null,
                    );
                  }
                  return const SizedBox.shrink();
                },
              ),
              BlocBuilder<CategoriesBloc, CategoriesState>(
                builder: (context, state) {
                  if (state is CategoriesLoadSuccess) {
                    return DropdownButtonFormField<int>(
                      initialValue: _selectedCategoryId,
                      decoration: const InputDecoration(labelText: 'Category'),
                      items: state.categories
                          .map((cat) => DropdownMenuItem<int>(
                                value: cat.id,
                                child: Text(cat.name),
                              ))
                          .toList(),
                      onChanged: (v) => setState(() => _selectedCategoryId = v),
                      validator: (v) =>
                          v == null ? 'Please select a category' : null,
                    );
                  }
                  return const SizedBox.shrink();
                },
              ),
              ListTile(
                title: Text("Date: ${_selectedDate.toLocal()}".split(' ')[0]),
                trailing: const Icon(Icons.calendar_today),
                onTap: () => _selectDate(context),
              )
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
        ElevatedButton(
          onPressed: _onSave,
          child: const Text('Save'),
        ),
      ],
    );
  }
}